//! AutoWiki contract + pure helpers (spec 001).
//!
//! The wiki is generated by a spawned agent that WRITES markdown pages + an
//! `index.json` TOC into `<workdir>/.agentum/wiki/`. This module owns the on-disk
//! contract (`WikiIndex` / `WikiPageMeta`), the strict parser (`parse_wiki_index`
//! — a garbled/empty index must NOT pass, mirroring
//! `harness::helpers::parse_qa_verdict`, so an inconclusive run never shows as a
//! success), the slug guard, and the generation-prompt builder. The HTTP surface
//! and the spawn/capture orchestration live in `routes::wiki`, which reuses these.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// On-disk schema version for `index.json`. Bump when the shape changes.
pub(crate) const WIKI_SCHEMA_VERSION: u32 = 1;

/// One entry in the wiki table of contents. `slug` is the page's filename stem
/// (`<slug>.md`) and URL segment; `title` is the human label and the `[[link]]`
/// target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct WikiPageMeta {
    pub slug: String,
    pub title: String,
}

/// The wiki TOC the agent writes to `.agentum/wiki/index.json`. Page order is
/// array order (no separate field — one less thing the agent can corrupt).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct WikiIndex {
    pub schema_version: u32,
    pub pages: Vec<WikiPageMeta>,
}

/// `<workdir>/.agentum/wiki` — where the agent writes pages and the routes read
/// them back.
pub(crate) fn wiki_dir(workdir: &Path) -> PathBuf {
    workdir.join(".agentum").join("wiki")
}

/// Slug guard: `^[a-z0-9][a-z0-9-]*$`. Rejects anything that could escape the wiki
/// dir (`..`, `/`, …) before it is joined to a path — path-traversal safety for
/// `GET /api/wiki/{slug}`.
pub(crate) fn is_valid_slug(slug: &str) -> bool {
    let mut chars = slug.chars();
    match chars.next() {
        Some(c) if c.is_ascii_lowercase() || c.is_ascii_digit() => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Parse + validate `index.json`. A missing/garbled/empty index is an error the
/// caller turns into a failed run — an inconclusive wiki must NOT be shown as a
/// success (AC-9), mirroring `harness::helpers::parse_qa_verdict`.
pub(crate) fn parse_wiki_index(json: &str) -> anyhow::Result<WikiIndex> {
    let index: WikiIndex = serde_json::from_str(json.trim())
        .map_err(|e| anyhow::anyhow!("wiki index.json is not valid JSON ({e})"))?;
    if index.schema_version != WIKI_SCHEMA_VERSION {
        anyhow::bail!(
            "wiki index.json schemaVersion {} unsupported (expected {})",
            index.schema_version,
            WIKI_SCHEMA_VERSION
        );
    }
    if index.pages.is_empty() {
        anyhow::bail!("wiki index.json lists no pages");
    }
    for page in &index.pages {
        if !is_valid_slug(&page.slug) {
            anyhow::bail!("wiki index.json has an invalid page slug: {:?}", page.slug);
        }
        if page.title.trim().is_empty() {
            anyhow::bail!("wiki page {:?} has an empty title", page.slug);
        }
    }
    Ok(index)
}

/// Build the generation prompt. `repo_context` is the `gather_repo_context` seed
/// (wired in `routes::wiki`); it is a *starter map*, not the mechanism — the agent
/// reads the repo from its workdir for anything the seed truncated. Built with
/// `push_str` (not `format!`) so the JSON example's braces need no escaping.
pub(crate) fn build_wiki_prompt(workdir: &str, repo_context: Option<&str>) -> String {
    let mut p = String::new();
    p.push_str(
        "You are the AutoWiki generator in the Agentum Harness. Produce a structured, \
         navigable wiki for THIS repository, which is checked out at:\n  ",
    );
    p.push_str(workdir);
    p.push_str("\n\n");

    if let Some(ctx) = repo_context {
        let ctx = ctx.trim();
        if !ctx.is_empty() {
            p.push_str(
                "=== STARTER MAP (a static snapshot — read more files on disk as needed) ===\n",
            );
            p.push_str(ctx);
            p.push_str("\n\n");
        }
    }

    p.push_str(
        "=== HOW TO ENUMERATE MODULES ===\n\
         Read the repo to decide the pages. Prefer, in order: (1) workspace members from \
         the root manifest (Cargo [workspace].members, package.json workspaces, \
         pnpm-workspace.yaml, go.mod, pyproject.toml); (2) conventional source roots \
         (crates/*, packages/*, apps/*, services/*, cmd/*); (3) else top-level \
         directories, excluding node_modules/target/dist/build/vendor/.git and dotdirs. \
         Cap at ~20 module pages; if there are more, summarize the rest on the \
         Architecture page and LIST which modules you omitted (never silently drop them).\n\n",
    );

    p.push_str("=== WRITE THESE FILES (under ");
    p.push_str(workdir);
    p.push_str("/.agentum/wiki/) ===\n");
    p.push_str(
        "- overview.md — what the project is, who it's for, and how to get started.\n\
         - architecture.md — the system shape. It MUST contain exactly one ```mermaid \
         block diagramming how the modules relate.\n\
         - one <slug>.md per enumerated module — its responsibility, key files, and how \
         it connects to the others.\n\
         - index.json — the table of contents, EXACTLY this shape (overview first, then \
         architecture, then the modules):\n  ",
    );
    p.push_str("{\"schemaVersion\": ");
    p.push_str(&WIKI_SCHEMA_VERSION.to_string());
    p.push_str(
        ", \"pages\": [{\"slug\": \"overview\", \"title\": \"Overview\"}, \
         {\"slug\": \"architecture\", \"title\": \"Architecture\"}, ...]}\n",
    );
    p.push_str(
        "Every slug must match ^[a-z0-9][a-z0-9-]*$ and have a matching <slug>.md file.\n\n\
         === LINKS ===\n\
         To link between pages, write [[Page Title]] where the title exactly matches \
         another page's title.\n\n\
         === RULES ===\n\
         Ground every page in what the code ACTUALLY does — read files, don't guess. Do \
         NOT stop until index.json and every page it lists exist on disk. Do NOT ask the \
         human anything; you have permission to read the repo and write the wiki files.",
    );
    p
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_wiki_index_accepts_a_well_formed_index() {
        let json = r#"{
            "schemaVersion": 1,
            "pages": [
                {"slug": "overview", "title": "Overview"},
                {"slug": "architecture", "title": "Architecture"},
                {"slug": "agentum-server", "title": "agentum-server"}
            ]
        }"#;
        let index = parse_wiki_index(json).expect("valid index should parse");
        assert_eq!(index.schema_version, 1);
        assert_eq!(index.pages.len(), 3);
        assert_eq!(index.pages[0].slug, "overview");
        assert_eq!(index.pages[2].title, "agentum-server");
    }

    #[test]
    fn parse_wiki_index_rejects_garbage() {
        assert!(parse_wiki_index("").is_err());
        assert!(parse_wiki_index("not json").is_err());
        assert!(parse_wiki_index("{}").is_err()); // missing required fields
    }

    #[test]
    fn parse_wiki_index_rejects_empty_pages() {
        assert!(parse_wiki_index(r#"{"schemaVersion": 1, "pages": []}"#).is_err());
    }

    #[test]
    fn parse_wiki_index_rejects_unsupported_schema_version() {
        let json = r#"{"schemaVersion": 2, "pages": [{"slug": "overview", "title": "Overview"}]}"#;
        assert!(parse_wiki_index(json).is_err());
    }

    #[test]
    fn parse_wiki_index_rejects_invalid_slug_or_empty_title() {
        let bad_slug = r#"{"schemaVersion": 1, "pages": [{"slug": "../etc", "title": "x"}]}"#;
        assert!(parse_wiki_index(bad_slug).is_err());
        let empty_title = r#"{"schemaVersion": 1, "pages": [{"slug": "overview", "title": "  "}]}"#;
        assert!(parse_wiki_index(empty_title).is_err());
    }

    #[test]
    fn is_valid_slug_guards_traversal() {
        assert!(is_valid_slug("overview"));
        assert!(is_valid_slug("agentum-server"));
        assert!(is_valid_slug("a1"));
        assert!(!is_valid_slug(""));
        assert!(!is_valid_slug("-leading"));
        assert!(!is_valid_slug("Upper"));
        assert!(!is_valid_slug("../etc/passwd"));
        assert!(!is_valid_slug("a/b"));
        assert!(!is_valid_slug("a.b"));
    }

    #[test]
    fn wiki_dir_is_under_dot_agentum() {
        let dir = wiki_dir(Path::new("/repo"));
        assert!(dir.ends_with("wiki"));
        assert!(dir.to_string_lossy().contains(".agentum"));
    }

    #[test]
    fn build_wiki_prompt_states_the_contract_and_seed() {
        let prompt = build_wiki_prompt("/repo/x", Some("SEED LINES"));
        assert!(prompt.contains("/repo/x"));
        assert!(prompt.contains("index.json"));
        assert!(prompt.contains("mermaid"));
        assert!(prompt.contains("SEED LINES"));
        assert!(prompt.to_lowercase().contains("do not stop"));
    }

    #[test]
    fn build_wiki_prompt_without_context_omits_seed() {
        let prompt = build_wiki_prompt("/repo/x", None);
        assert!(!prompt.contains("STARTER MAP"));
    }
}
