mod bridge;
mod commands;
mod computer;
mod path_env;
// The Voice STT engine. Named `speech_engine` (not `speech`) to avoid colliding
// with the `commands::speech` module imported below for the invoke_handler.
#[path = "speech/mod.rs"]
mod speech_engine;
mod state;

use commands::{
    accounts, agent_status, app, browser, browser_native, cache, claude_usage, cli, clipboard,
    codex_usage, crash_reports, diagnostics, e2e, feedback, fs, gh, gh_projects, gl, hooks,
    hosted_review, html_export, keybindings, linear, mobile, notebook, notifications, onboarding,
    open_code_usage, permissions, pet, project_groups, pty, rate_limits, remote_workspace, repos,
    runtime, server, session, settings, shell, shell_runtimes, skills, sparse_presets, speech, ssh,
    star_nag, stats, telemetry, ui, updater, window, workspace_cleanup, workspace_ports,
    workspace_space,
};
use state::AppState;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // GUI launches (Finder/Dock, .desktop/AppImage) inherit a minimal PATH that
    // omits ~/.local/bin, Homebrew, and node version-manager shims where the
    // agent CLIs and gh/glab live. Hydrate from the login shell before anything
    // (plugins, the embedded server's `which` probes, child PTYs) reads PATH,
    // otherwise detection reports "No agents detected" on installed tools.
    path_env::hydrate_path_from_login_shell();

    tauri::Builder::default()
        .plugin(
            tauri_plugin_log::Builder::default()
                .level(log::LevelFilter::Info)
                .build(),
        )
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_notification::init())
        .setup(|app| {
            let state = AppState::new().map_err(|error| {
                Box::<dyn std::error::Error>::from(std::io::Error::other(error.to_string()))
            })?;
            app.manage(state);

            // Boot agentum-server in-process on a loopback port and expose its
            // URL to the webview. Block here so the endpoint is ready before the
            // React app asks for it; the server itself runs on background tasks.
            // Install a DesktopBridge so the embedded server's /api/browser and
            // /api/computer routes can drive THIS process's webviews + the macOS
            // AX engine (the only process that can). Standalone daemons get no
            // bridge and 501 those routes.
            let bridge = std::sync::Arc::new(bridge::TauriBridge::new(app.handle().clone()));
            let addr = tauri::async_runtime::block_on(async {
                let (store, _db_path) = agentum_store::open_default()
                    .await
                    .map_err(|e| std::io::Error::other(e.to_string()))?;
                agentum_server::serve_embedded_loopback_with_bridge(store, bridge)
                    .await
                    .map_err(|e| std::io::Error::other(e.to_string()))
            })?;
            app.manage(server::ServerEndpoint {
                url: format!("http://{addr}"),
                token: None,
            });

            // On-device speech-to-text state (Voice dictation). Models live under
            // the app data dir; failing to resolve it must not block app boot, so
            // fall back to a temp dir and let downloads surface any error.
            let models_dir = app
                .path()
                .app_data_dir()
                .map(|d| d.join("speech-models"))
                .unwrap_or_else(|_| std::env::temp_dir().join("agentum-speech-models"));
            match speech_engine::SpeechState::new(models_dir) {
                Ok(speech_state) => {
                    app.manage(speech_state);
                }
                Err(error) => log::error!("speech state init failed: {error}"),
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            server::app_get_server_endpoint,
            pty::pty_create,
            pty::pty_write,
            pty::pty_resize,
            pty::pty_kill,
            pty::pty_write_accepted,
            pty::pty_pause_output,
            pty::pty_has_child_processes,
            pty::pty_list_sessions,
            fs::fs_read_file,
            fs::fs_write_file,
            fs::fs_read_dir,
            fs::fs_create_file,
            fs::fs_create_dir,
            fs::fs_rename,
            fs::fs_copy,
            fs::fs_delete_path,
            fs::fs_stat,
            fs::fs_authorize_external_path,
            fs::fs_list_files,
            fs::fs_list_markdown_documents,
            fs::fs_search,
            fs::fs_import_external_paths,
            fs::fs_stage_external_paths_for_runtime_upload,
            fs::fs_resolve_dropped_paths_for_agent,
            fs::fs_exists,
            fs::fs_mkdir,
            fs::fs_remove,
            fs::fs_watch_worktree,
            fs::fs_unwatch_worktree,
            app::app_get_identity,
            app::app_get_platform,
            app::app_relaunch,
            app::app_get_version,
            app::app_restart,
            app::app_reload,
            app::app_get_keyboard_input_source_id,
            app::app_set_unread_dock_badge_count,
            app::app_get_floating_terminal_cwd,
            app::app_get_floating_markdown_directory,
            app::app_pick_floating_workspace_directory,
            app::app_pick_floating_markdown_document,
            window::window_set_title,
            window::window_minimize,
            window::window_maximize,
            window::window_close,
            window::window_set_size,
            settings::settings_get,
            settings::settings_set,
            settings::settings_get_all,
            settings::settings_list_fonts,
            settings::settings_preview_ghostty_import,
            shell::shell_get_default,
            shell::shell_open_external,
            shell::shell_open_path,
            shell::shell_open_url,
            shell::shell_open_file_uri,
            shell::shell_open_file_path,
            shell::shell_path_exists,
            shell::shell_copy_file,
            shell::shell_pick_directory,
            shell::shell_pick_image,
            shell::shell_pick_audio,
            shell::shell_pick_attachment,
            shell::shell_open_in_file_manager,
            shell::shell_open_in_external_editor,
            shell::shell_pick_repo_icon_image,
            ssh::ssh_list_hosts,
            ssh::ssh_connect,
            ssh::ssh_list_targets,
            ssh::ssh_add_target,
            ssh::ssh_update_target,
            ssh::ssh_remove_target,
            ssh::ssh_import_config,
            ssh::ssh_get_state,
            ssh::ssh_needs_passphrase_prompt,
            ssh::ssh_list_port_forwards,
            ssh::ssh_add_port_forward,
            ssh::ssh_update_port_forward,
            ssh::ssh_remove_port_forward,
            ssh::ssh_list_detected_ports,
            ui::ui_get,
            ui::ui_record_feature_interaction,
            ui::ui_write_clipboard_text,
            ui::ui_read_clipboard_text,
            ui::ui_minimize,
            ui::ui_maximize,
            ui::ui_is_maximized,
            ui::ui_request_close,
            ui::ui_set,
            ui::ui_get_zoom_level,
            ui::ui_set_zoom_level,
            ui::ui_set_markdown_editor_focused,
            ui::ui_set_terminal_input_focused,
            ui::ui_set_shortcut_recorder_focused,
            ui::ui_reply_tab_create,
            ui::ui_reply_tab_set_profile,
            ui::ui_reply_tab_close,
            ui::ui_reply_terminal_create,
            ui::ui_sync_traffic_lights,
            ui::ui_popup_menu,
            ui::ui_confirm_window_close,
            remote_workspace::remote_workspace_get,
            remote_workspace::remote_workspace_set_for_connected_targets,
            session::session_get,
            session::session_set,
            session::session_set_sync,
            session::session_patch,
            pet::pet_import,
            pet::pet_import_pet_bundle,
            pet::pet_read,
            pet::pet_delete,
            workspace_cleanup::workspace_cleanup_dismiss,
            workspace_cleanup::workspace_cleanup_clear_dismissals,
            shell_runtimes::pwsh_is_available,
            shell_runtimes::wsl_is_available,
            shell_runtimes::wsl_list_distros,
            skills::skills_discover,
            hosted_review::hosted_review_for_branch,
            hooks::hooks_check,
            hooks::hooks_inspect_setup_script_imports,
            hooks::hooks_read_issue_command,
            hooks::hooks_write_issue_command,
            html_export::export_html_to_pdf,
            gh::gh_repo_slug,
            gh::gh_enqueue_pr_refresh,
            gh::gh_update_issue,
            gh::gh_merge_pr,
            gh::gh_set_pr_auto_merge,
            gh::gh_request_pr_reviewers,
            gh::gh_update_pr_state,
            gh::gh_remove_pr_reviewers,
            gh::gh_rerun_pr_checks,
            gh::gh_create_issue,
            gh::gh_rate_limit,
            gh::gh_star_agentum,
            gh::gh_set_pr_file_viewed,
            gh::gh_update_pr_title,
            gh::gh_check_agentum_starred,
            gh::gh_work_item,
            gh::gh_work_item_by_owner_repo,
            gh::gh_work_item_details,
            gh::gh_issue,
            gh::gh_pr_check_details,
            gh::gh_pr_checks,
            gh::gh_count_work_items,
            gl::gl_list_labels,
            gl::gl_list_assignable_users,
            gl::gl_work_item_details,
            gl::gl_rate_limit,
            gl::gl_job_trace,
            gl::gl_retry_job,
            gl::gl_update_mr,
            gl::gl_close_mr,
            gl::gl_reopen_mr,
            gl::gl_merge_mr,
            linear::linear_list_issues,
            linear::linear_search_issues,
            linear::linear_list_teams,
            linear::linear_team_states,
            linear::linear_team_labels,
            linear::linear_team_members,
            linear::linear_issue_comments,
            linear::linear_list_projects,
            linear::linear_list_project_issues,
            linear::linear_list_custom_views,
            linear::linear_list_custom_view_issues,
            linear::linear_list_custom_view_projects,
            linear::linear_get_issue,
            linear::linear_get_project,
            linear::linear_get_custom_view,
            linear::linear_disconnect,
            cache::cache_get_git_hub,
            cache::cache_set_git_hub,
            notebook::notebook_run_python_cell,
            permissions::computer_use_permissions_get_status,
            permissions::computer_use_permissions_open_setup,
            permissions::computer_use_permissions_reset,
            permissions::developer_permissions_request,
            // Repo registry + git-ref logic moved to agentum-server (routes/repos.rs);
            // only the native folder-picker dialog remains here.
            repos::repos_pick_folder,
            repos::repos_pick_directory,
            project_groups::project_groups_list,
            project_groups::project_groups_create,
            project_groups::project_groups_update,
            project_groups::project_groups_delete,
            project_groups::project_groups_move_project,
            project_groups::project_groups_scan_nested,
            project_groups::project_groups_import_nested,
            speech::speech_get_catalog,
            speech::speech_get_model_states,
            speech::speech_download_model,
            speech::speech_cancel_download,
            speech::speech_delete_model,
            speech::speech_start_dictation,
            speech::speech_start_capture,
            speech::speech_stop_capture,
            speech::speech_feed_audio,
            speech::speech_stop_dictation,
            diagnostics::diagnostics_open_trace_folder,
            diagnostics::diagnostics_clear_traces,
            diagnostics::diagnostics_open_bundle_preview,
            diagnostics::diagnostics_discard_bundle_preview,
            diagnostics::diagnostics_delete_bundle,
            onboarding::onboarding_get,
            onboarding::onboarding_update,
            crash_reports::crash_reports_get_latest_pending,
            crash_reports::crash_reports_get_latest_report,
            crash_reports::crash_reports_dismiss,
            crash_reports::crash_reports_record_breadcrumb,
            crash_reports::crash_reports_record_renderer_error,
            crash_reports::crash_reports_submit,
            crash_reports::crash_reports_copy_latest_diagnostics,
            workspace_ports::workspace_ports_scan,
            workspace_ports::workspace_ports_kill,
            browser_native::browser_webview_open,
            browser_native::browser_webview_navigate,
            browser_native::browser_webview_history,
            browser_native::browser_webview_set_bounds,
            browser_native::browser_webview_set_visible,
            browser_native::browser_webview_close,
            browser_native::browser_webview_state,
            browser::browser_unregister_guest,
            browser::browser_open_dev_tools,
            browser::browser_cancel_download,
            browser::browser_cancel_grab,
            browser::browser_session_list_profiles,
            browser::browser_session_detect_browsers,
            browser::browser_session_delete_profile,
            browser::browser_session_clear_default_cookies,
            browser::browser_notify_active_tab_changed,
            updater::updater_get_version,
            updater::updater_get_status,
            updater::updater_check,
            updater::updater_download,
            updater::updater_quit_and_install,
            updater::updater_dismiss_nudge,
            permissions::agent_trust_mark_trusted,
            permissions::developer_permissions_get_status,
            permissions::developer_permissions_open_settings,
            rate_limits::rate_limits_get,
            rate_limits::rate_limits_refresh,
            rate_limits::rate_limits_refresh_codex_for_target,
            rate_limits::rate_limits_refresh_claude_for_target,
            rate_limits::rate_limits_set_polling_interval,
            rate_limits::rate_limits_fetch_inactive_claude_accounts,
            rate_limits::rate_limits_fetch_inactive_codex_accounts,
            claude_usage::claude_usage_get_scan_state,
            claude_usage::claude_usage_set_enabled,
            claude_usage::claude_usage_refresh,
            claude_usage::claude_usage_get_summary,
            claude_usage::claude_usage_get_daily,
            claude_usage::claude_usage_get_breakdown,
            claude_usage::claude_usage_get_recent_sessions,
            codex_usage::codex_usage_get_scan_state,
            codex_usage::codex_usage_set_enabled,
            codex_usage::codex_usage_refresh,
            codex_usage::codex_usage_get_summary,
            codex_usage::codex_usage_get_daily,
            codex_usage::codex_usage_get_breakdown,
            codex_usage::codex_usage_get_recent_sessions,
            open_code_usage::open_code_usage_get_scan_state,
            open_code_usage::open_code_usage_set_enabled,
            open_code_usage::open_code_usage_refresh,
            open_code_usage::open_code_usage_get_summary,
            open_code_usage::open_code_usage_get_daily,
            open_code_usage::open_code_usage_get_breakdown,
            open_code_usage::open_code_usage_get_recent_sessions,
            agent_status::agent_status_get_snapshot,
            agent_status::agent_status_infer_interrupt,
            agent_status::agent_status_get_migration_unsupported_snapshot,
            agent_status::agent_status_drop,
            accounts::claude_accounts_list,
            accounts::claude_accounts_select,
            accounts::claude_accounts_add,
            accounts::claude_accounts_begin_add,
            accounts::claude_accounts_live_login,
            accounts::claude_accounts_sync_current,
            accounts::claude_accounts_reauthenticate,
            accounts::claude_accounts_remove,
            accounts::codex_accounts_list,
            accounts::codex_accounts_select,
            accounts::codex_accounts_add,
            accounts::codex_accounts_begin_add,
            accounts::codex_accounts_live_login,
            accounts::codex_accounts_sync_current,
            accounts::codex_accounts_reauthenticate,
            accounts::codex_accounts_remove,
            feedback::feedback_submit,
            sparse_presets::sparse_presets_list,
            sparse_presets::sparse_presets_remove,
            star_nag::star_nag_dismiss,
            star_nag::star_nag_complete,
            star_nag::star_nag_force_show,
            runtime::runtime_get_status,
            runtime::runtime_get_terminal_fit_overrides,
            runtime::runtime_get_terminal_drivers,
            runtime::runtime_get_browser_drivers,
            runtime::runtime_reclaim_browser_for_desktop,
            clipboard::clipboard_read,
            clipboard::clipboard_write,
            cli::cli_get_install_status,
            cli::cli_install,
            cli::cli_remove,
            cli::cli_get_wsl_install_status,
            cli::cli_install_wsl,
            cli::cli_remove_wsl,
            keybindings::keybindings_get,
            keybindings::keybindings_reload,
            keybindings::keybindings_ensure_file,
            keybindings::keybindings_set_action,
            keybindings::keybindings_open_file,
            keybindings::keybindings_reveal_file,
            notifications::notifications_dispatch,
            notifications::notifications_get_permission_status,
            notifications::notifications_request_permission,
            notifications::notifications_open_system_settings,
            notifications::notifications_play_sound,
            // --- Remaining ported command surface (stubs with safe defaults) ---
            gh::gh_update_pull_request_by_slug,
            gh::gh_update_issue_by_slug,
            gh::gh_add_issue_comment,
            gh::gh_add_pr_review_comment_reply,
            gh::gh_add_pr_review_comment,
            gh_projects::gh_list_project_views,
            gh::gh_list_work_items,
            gh::gh_refresh_pr_now,
            gh_projects::gh_list_accessible_projects,
            gh_projects::gh_resolve_project_ref,
            gh::gh_delete_issue_comment_by_slug,
            gh::gh_update_issue_comment_by_slug,
            gh::gh_add_issue_comment_by_slug,
            gh::gh_list_issue_types_by_slug,
            gh::gh_list_labels_by_slug,
            gh::gh_list_assignable_users_by_slug,
            gh_projects::gh_get_project_view_table,
            gh::gh_update_project_item_field,
            gh::gh_clear_project_item_field,
            gh::gh_update_issue_type_by_slug,
            gh::gh_pr_comments,
            gh::gh_resolve_review_thread,
            gh::gh_report_visible_pr_refresh_candidates,
            pty::pty_get_main_buffer_snapshot,
            pty::pty_get_foreground_process,
            pty::pty_clear_pending_pane_serializer,
            pty::pty_management,
            pty::pty_management_list_sessions,
            pty::pty_management_kill_one,
            pty::pty_management_kill_all,
            pty::pty_management_restart,
            pty::pty_ack_cold_restore,
            pty::pty_declare_pending_pane_serializer,
            pty::pty_settle_pane_serializer,
            pty::pty_signal,
            pty::pty_send_serialized_buffer,
            pty::pty_get_cwd,
            pty::pty_spawn,
            pty::pty_report_geometry,
            telemetry::telemetry_track,
            telemetry::telemetry_set_opt_in,
            telemetry::telemetry_acknowledge_banner,
            telemetry::telemetry_get_consent_state,
            mobile::mobile_get_runtime_pairing_url,
            mobile::mobile_list_network_interfaces,
            mobile::mobile_list_runtime_access_grants,
            mobile::mobile_revoke_runtime_access,
            browser::browser_set_grab_mode,
            browser::browser_capture_selection_screenshot,
            browser::browser_set_viewport_override,
            browser::browser_await_grab_selection,
            browser::browser_extract_hover_payload,
            browser::browser_accept_download,
            browser::browser_session_create_profile,
            browser::browser_session_import_cookies,
            browser::browser_session_import_from_browser,
            ssh::ssh_submit_credential,
            ssh::ssh_terminate_sessions,
            ssh::ssh_disconnect,
            ssh::ssh_browse_dir,
            ssh::ssh_reset_relay,
            ssh::ssh_test_connection,
            linear::linear_status,
            linear::linear_test_connection,
            linear::linear_connect,
            linear::linear_select_workspace,
            linear::linear_create_issue,
            linear::linear_update_issue,
            linear::linear_add_issue_comment,
            gl::gl_resolve_mr_discussion,
            gl::gl_update_mr_reviewers,
            gl::gl_add_mr_inline_comment,
            gl::gl_add_mr_comment,
            gl::gl_add_issue_comment,
            gl::gl_list_m_rs,
            runtime::runtime_call,
            runtime::runtime_sync_window_graph,
            runtime::runtime_environments_call,
            runtime::runtime_environments_subscribe,
            diagnostics::diagnostics_get_status,
            diagnostics::diagnostics_collect_bundle,
            diagnostics::diagnostics_upload_bundle,
            ui::ui_save_clipboard_image_as_temp_file,
            ui::ui_write_clipboard_image,
            workspace_cleanup::workspace_cleanup_scan,
            hosted_review::hosted_review_get_creation_eligibility,
            hosted_review::hosted_review_create,
            sparse_presets::sparse_presets_save,
            shell_runtimes::git_bash_is_available,
            e2e::e2e_get_config,
            stats::stats_get_summary,
            workspace_space::workspace_space_cancel,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
