// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const agentTrust = defineNamespace('agentTrust', {
  markTrusted: (...args: any[]) => call('agent_trust_mark_trusted', args),
}) satisfies AgentumApi['agentTrust']
