// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const agentStatus = defineNamespace('agentStatus', {
  drop: (...args: any[]) => call('agent_status_drop', args),
  getMigrationUnsupportedSnapshot: (...args: any[]) => call('agent_status_get_migration_unsupported_snapshot', args),
  getSnapshot: (...args: any[]) => call('agent_status_get_snapshot', args),
  inferInterrupt: (...args: any[]) => call('agent_status_infer_interrupt', args),
  onMigrationUnsupported: (cb: (p: any) => void) => subscribe('agent-status-migration-unsupported', cb),
  onMigrationUnsupportedClear: (cb: (p: any) => void) => subscribe('agent-status-migration-unsupported-clear', cb),
  onSet: (cb: (p: any) => void) => subscribe('agent-status-set', cb),
}) satisfies AgentumApi['agentStatus']
