// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const app = defineNamespace('app', {
  getFloatingMarkdownDirectory: (...args: any[]) => call('app_get_floating_markdown_directory', args),
  getFloatingTerminalCwd: (...args: any[]) => call('app_get_floating_terminal_cwd', args),
  getKeyboardInputSourceId: (...args: any[]) => call('app_get_keyboard_input_source_id', args),
  pickFloatingMarkdownDocument: (...args: any[]) => call('app_pick_floating_markdown_document', args),
  pickFloatingWorkspaceDirectory: (...args: any[]) => call('app_pick_floating_workspace_directory', args),
  relaunch: (...args: any[]) => call('app_relaunch', args),
  reload: (...args: any[]) => call('app_reload', args),
  restart: (...args: any[]) => call('app_restart', args),
  setUnreadDockBadgeCount: (...args: any[]) => call('app_set_unread_dock_badge_count', args),
}) satisfies AgentumApi['app']
