// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const automations = defineNamespace('automations', {
  create: (...args: any[]) => call('automations_create', args),
  createExternal: (...args: any[]) => call('automations_create_external', args),
  delete: (...args: any[]) => call('automations_delete', args),
  list: (...args: any[]) => call('automations_list', args),
  listExternalManagers: (...args: any[]) => call('automations_list_external_managers', args),
  listRuns: (...args: any[]) => call('automations_list_runs', args),
  markDispatchResult: (...args: any[]) => call('automations_mark_dispatch_result', args),
  rendererReady: (...args: any[]) => call('automations_renderer_ready', args),
  runExternalAction: (...args: any[]) => call('automations_run_external_action', args),
  runNow: (...args: any[]) => call('automations_run_now', args),
  runPrecheck: (...args: any[]) => call('automations_run_precheck', args),
  update: (...args: any[]) => call('automations_update', args),
  updateExternal: (...args: any[]) => call('automations_update_external', args),
  onDispatchRequested: (cb: (p: any) => void) => subscribe('automations-dispatch-requested', cb),
}) satisfies AgentumApi['automations']
