// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const browser = defineNamespace('browser', {
  acceptDownload: (...args: any[]) => call('browser_accept_download', args),
  awaitGrabSelection: (...args: any[]) => call('browser_await_grab_selection', args),
  cancelDownload: (...args: any[]) => call('browser_cancel_download', args),
  cancelGrab: (...args: any[]) => call('browser_cancel_grab', args),
  captureSelectionScreenshot: (...args: any[]) => call('browser_capture_selection_screenshot', args),
  extractHoverPayload: (...args: any[]) => call('browser_extract_hover_payload', args),
  inpageAnnotate: (...args: any[]) => call('browser_inpage_annotate', args),
  notifyActiveTabChanged: (...args: any[]) => call('browser_notify_active_tab_changed', args),
  openDevTools: (...args: any[]) => call('browser_open_dev_tools', args),
  sessionClearDefaultCookies: (...args: any[]) => call('browser_session_clear_default_cookies', args),
  sessionCreateProfile: (...args: any[]) => call('browser_session_create_profile', args),
  sessionDeleteProfile: (...args: any[]) => call('browser_session_delete_profile', args),
  sessionDetectBrowsers: (...args: any[]) => call('browser_session_detect_browsers', args),
  sessionImportCookies: (...args: any[]) => call('browser_session_import_cookies', args),
  sessionImportFromBrowser: (...args: any[]) => call('browser_session_import_from_browser', args),
  sessionListProfiles: (...args: any[]) => call('browser_session_list_profiles', args),
  setGrabMode: (...args: any[]) => call('browser_set_grab_mode', args),
  setViewportOverride: (...args: any[]) => call('browser_set_viewport_override', args),
  unregisterGuest: (...args: any[]) => call('browser_unregister_guest', args),
  onActivateView: (cb: (p: any) => void) => subscribe('browser-activate-view', cb),
  onContextMenuDismissed: (cb: (p: any) => void) => subscribe('browser-context-menu-dismissed', cb),
  onContextMenuRequested: (cb: (p: any) => void) => subscribe('browser-context-menu-requested', cb),
  onDownloadFinished: (cb: (p: any) => void) => subscribe('browser-download-finished', cb),
  onDownloadProgress: (cb: (p: any) => void) => subscribe('browser-download-progress', cb),
  onDownloadRequested: (cb: (p: any) => void) => subscribe('browser-download-requested', cb),
  onGrabActionShortcut: (cb: (p: any) => void) => subscribe('browser-grab-action-shortcut', cb),
  onGrabModeToggle: (cb: (p: any) => void) => subscribe('browser-grab-mode-toggle', cb),
  onGuestLoadFailed: (cb: (p: any) => void) => subscribe('browser-guest-load-failed', cb),
  onInpageAnnotation: (cb: (p: any) => void) => subscribe('browser-inpage-annotation', cb),
  onNavigationUpdate: (cb: (p: any) => void) => subscribe('browser-navigation-update', cb),
  onOpenLinkInAgentumTab: (cb: (p: any) => void) => subscribe('browser-open-link-in-agentum-tab', cb),
  onPaneFocus: (cb: (p: any) => void) => subscribe('browser-pane-focus', cb),
  onPermissionDenied: (cb: (p: any) => void) => subscribe('browser-permission-denied', cb),
  onPopup: (cb: (p: any) => void) => subscribe('browser-popup', cb),
}) satisfies AgentumApi['browser']
