// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const cache = defineNamespace('cache', {
  getGitHub: (...args: any[]) => call('cache_get_git_hub', args),
  setGitHub: (...args: any[]) => call('cache_set_git_hub', args),
}) satisfies AgentumApi['cache']
