// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const claudeAccounts = defineNamespace('claudeAccounts', {
  add: (...args: any[]) => call('claude_accounts_add', args),
  list: (...args: any[]) => call('claude_accounts_list', args),
  reauthenticate: (...args: any[]) => call('claude_accounts_reauthenticate', args),
  remove: (...args: any[]) => call('claude_accounts_remove', args),
  select: (...args: any[]) => call('claude_accounts_select', args),
}) satisfies AgentumApi['claudeAccounts']
