// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const cli = defineNamespace('cli', {
  getInstallStatus: (...args: any[]) => call('cli_get_install_status', args),
  getWslInstallStatus: (...args: any[]) => call('cli_get_wsl_install_status', args),
  install: (...args: any[]) => call('cli_install', args),
  installWsl: (...args: any[]) => call('cli_install_wsl', args),
  remove: (...args: any[]) => call('cli_remove', args),
  removeWsl: (...args: any[]) => call('cli_remove_wsl', args),
}) satisfies AgentumApi['cli']
