// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const codexUsage = defineNamespace('codexUsage', {
  getBreakdown: (...args: any[]) => call('codex_usage_get_breakdown', args),
  getDaily: (...args: any[]) => call('codex_usage_get_daily', args),
  getRecentSessions: (...args: any[]) => call('codex_usage_get_recent_sessions', args),
  getScanState: (...args: any[]) => call('codex_usage_get_scan_state', args),
  getSummary: (...args: any[]) => call('codex_usage_get_summary', args),
  refresh: (...args: any[]) => call('codex_usage_refresh', args),
  setEnabled: (...args: any[]) => call('codex_usage_set_enabled', args),
}) satisfies AgentumApi['codexUsage']
