// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const computerUsePermissions = defineNamespace('computerUsePermissions', {
  getStatus: (...args: any[]) => call('computer_use_permissions_get_status', args),
  openSetup: (...args: any[]) => call('computer_use_permissions_open_setup', args),
  reset: (...args: any[]) => call('computer_use_permissions_reset', args),
}) satisfies AgentumApi['computerUsePermissions']
