// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.
export type ApiMethod = (...args: any[]) => Promise<any>
export type ApiEvent = (callback: (payload: any) => void) => () => void

export interface AgentumApi {
  agentStatus: {
    drop: ApiMethod
    getMigrationUnsupportedSnapshot: ApiMethod
    getSnapshot: ApiMethod
    inferInterrupt: ApiMethod
    onMigrationUnsupported: ApiEvent
    onMigrationUnsupportedClear: ApiEvent
    onSet: ApiEvent
  }
  agentTrust: {
    markTrusted: ApiMethod
  }
  app: {
    getFloatingMarkdownDirectory: ApiMethod
    getFloatingTerminalCwd: ApiMethod
    getKeyboardInputSourceId: ApiMethod
    pickFloatingMarkdownDocument: ApiMethod
    pickFloatingWorkspaceDirectory: ApiMethod
    relaunch: ApiMethod
    reload: ApiMethod
    restart: ApiMethod
    setUnreadDockBadgeCount: ApiMethod
  }
  automations: {
    create: ApiMethod
    createExternal: ApiMethod
    delete: ApiMethod
    list: ApiMethod
    listExternalManagers: ApiMethod
    listRuns: ApiMethod
    markDispatchResult: ApiMethod
    rendererReady: ApiMethod
    runExternalAction: ApiMethod
    runNow: ApiMethod
    runPrecheck: ApiMethod
    update: ApiMethod
    updateExternal: ApiMethod
    onDispatchRequested: ApiEvent
  }
  browser: {
    acceptDownload: ApiMethod
    awaitGrabSelection: ApiMethod
    cancelDownload: ApiMethod
    cancelGrab: ApiMethod
    captureSelectionScreenshot: ApiMethod
    extractHoverPayload: ApiMethod
    notifyActiveTabChanged: ApiMethod
    openDevTools: ApiMethod
    sessionClearDefaultCookies: ApiMethod
    sessionCreateProfile: ApiMethod
    sessionDeleteProfile: ApiMethod
    sessionDetectBrowsers: ApiMethod
    sessionImportCookies: ApiMethod
    sessionImportFromBrowser: ApiMethod
    sessionListProfiles: ApiMethod
    setGrabMode: ApiMethod
    setViewportOverride: ApiMethod
    unregisterGuest: ApiMethod
    onActivateView: ApiEvent
    onContextMenuDismissed: ApiEvent
    onContextMenuRequested: ApiEvent
    onDownloadFinished: ApiEvent
    onDownloadProgress: ApiEvent
    onDownloadRequested: ApiEvent
    onGrabActionShortcut: ApiEvent
    onGrabModeToggle: ApiEvent
    onGuestLoadFailed: ApiEvent
    onNavigationUpdate: ApiEvent
    onOpenLinkInAgentumTab: ApiEvent
    onPaneFocus: ApiEvent
    onPermissionDenied: ApiEvent
    onPopup: ApiEvent
  }
  cache: {
    getGitHub: ApiMethod
    setGitHub: ApiMethod
  }
  claudeAccounts: {
    add: ApiMethod
    list: ApiMethod
    reauthenticate: ApiMethod
    remove: ApiMethod
    select: ApiMethod
  }
  claudeUsage: {
    getBreakdown: ApiMethod
    getDaily: ApiMethod
    getRecentSessions: ApiMethod
    getScanState: ApiMethod
    getSummary: ApiMethod
    refresh: ApiMethod
    setEnabled: ApiMethod
  }
  cli: {
    getInstallStatus: ApiMethod
    getWslInstallStatus: ApiMethod
    install: ApiMethod
    installWsl: ApiMethod
    remove: ApiMethod
    removeWsl: ApiMethod
  }
  codexAccounts: {
    add: ApiMethod
    list: ApiMethod
    reauthenticate: ApiMethod
    remove: ApiMethod
    select: ApiMethod
  }
  codexUsage: {
    getBreakdown: ApiMethod
    getDaily: ApiMethod
    getRecentSessions: ApiMethod
    getScanState: ApiMethod
    getSummary: ApiMethod
    refresh: ApiMethod
    setEnabled: ApiMethod
  }
  computerUsePermissions: {
    getStatus: ApiMethod
    openSetup: ApiMethod
    reset: ApiMethod
  }
  crashReports: {
    copyLatestDiagnostics: ApiMethod
    dismiss: ApiMethod
    getLatestPending: ApiMethod
    getLatestReport: ApiMethod
    submit: ApiMethod
  }
  developerPermissions: {
    getStatus: ApiMethod
    request: ApiMethod
  }
  diagnostics: {
    clearTraces: ApiMethod
    collectBundle: ApiMethod
    deleteBundle: ApiMethod
    discardBundlePreview: ApiMethod
    getStatus: ApiMethod
    openBundlePreview: ApiMethod
    openTraceFolder: ApiMethod
    uploadBundle: ApiMethod
  }
  e2e: {
    getConfig: ApiMethod
  }
  export: {
    htmlToPdf: ApiMethod
  }
  feedback: {
    submit: ApiMethod
  }
  fs: {
    authorizeExternalPath: ApiMethod
    copy: ApiMethod
    createDir: ApiMethod
    createFile: ApiMethod
    deletePath: ApiMethod
    importExternalPaths: ApiMethod
    listFiles: ApiMethod
    listMarkdownDocuments: ApiMethod
    readDir: ApiMethod
    readFile: ApiMethod
    rename: ApiMethod
    resolveDroppedPathsForAgent: ApiMethod
    search: ApiMethod
    stageExternalPathsForRuntimeUpload: ApiMethod
    stat: ApiMethod
    unwatchWorktree: ApiMethod
    writeFile: ApiMethod
    onFsChanged: ApiEvent
  }
  gh: {
    addIssueComment: ApiMethod
    addIssueCommentBySlug: ApiMethod
    addPRReviewComment: ApiMethod
    addPRReviewCommentReply: ApiMethod
    checkAgentumStarred: ApiMethod
    clearProjectItemField: ApiMethod
    countWorkItems: ApiMethod
    createIssue: ApiMethod
    deleteIssueCommentBySlug: ApiMethod
    enqueuePRRefresh: ApiMethod
    getProjectViewTable: ApiMethod
    issue: ApiMethod
    listAccessibleProjects: ApiMethod
    listAssignableUsersBySlug: ApiMethod
    listIssueTypesBySlug: ApiMethod
    listLabelsBySlug: ApiMethod
    listProjectViews: ApiMethod
    listWorkItems: ApiMethod
    mergePR: ApiMethod
    prCheckDetails: ApiMethod
    prChecks: ApiMethod
    prComments: ApiMethod
    rateLimit: ApiMethod
    refreshPRNow: ApiMethod
    removePRReviewers: ApiMethod
    repoSlug: ApiMethod
    reportVisiblePRRefreshCandidates: ApiMethod
    requestPRReviewers: ApiMethod
    rerunPRChecks: ApiMethod
    resolveProjectRef: ApiMethod
    resolveReviewThread: ApiMethod
    setPRAutoMerge: ApiMethod
    setPRFileViewed: ApiMethod
    starAgentum: ApiMethod
    updateIssue: ApiMethod
    updateIssueBySlug: ApiMethod
    updateIssueCommentBySlug: ApiMethod
    updateIssueTypeBySlug: ApiMethod
    updatePRState: ApiMethod
    updatePRTitle: ApiMethod
    updateProjectItemField: ApiMethod
    updatePullRequestBySlug: ApiMethod
    workItem: ApiMethod
    workItemByOwnerRepo: ApiMethod
    workItemDetails: ApiMethod
    onPRRefreshEvent: ApiEvent
    onWorkItemMutated: ApiEvent
  }
  git: {
    abortMerge: ApiMethod
    abortRebase: ApiMethod
    branchCompare: ApiMethod
    branchDiff: ApiMethod
    bulkDiscard: ApiMethod
    bulkStage: ApiMethod
    bulkUnstage: ApiMethod
    cancelGenerateCommitMessage: ApiMethod
    cancelGeneratePullRequestFields: ApiMethod
    checkIgnored: ApiMethod
    commit: ApiMethod
    commitCompare: ApiMethod
    commitDiff: ApiMethod
    conflictOperation: ApiMethod
    diff: ApiMethod
    discard: ApiMethod
    discoverCommitMessageModels: ApiMethod
    fastForward: ApiMethod
    fetch: ApiMethod
    generateCommitMessage: ApiMethod
    generatePullRequestFields: ApiMethod
    history: ApiMethod
    pull: ApiMethod
    push: ApiMethod
    rebaseFromBase: ApiMethod
    remoteFileUrl: ApiMethod
    stage: ApiMethod
    status: ApiMethod
    unstage: ApiMethod
    upstreamStatus: ApiMethod
  }
  gitBash: {
    isAvailable: ApiMethod
  }
  gl: {
    addIssueComment: ApiMethod
    addMRComment: ApiMethod
    addMRInlineComment: ApiMethod
    closeMR: ApiMethod
    jobTrace: ApiMethod
    listAssignableUsers: ApiMethod
    listLabels: ApiMethod
    listMRs: ApiMethod
    mergeMR: ApiMethod
    rateLimit: ApiMethod
    reopenMR: ApiMethod
    resolveMRDiscussion: ApiMethod
    retryJob: ApiMethod
    updateMR: ApiMethod
    updateMRReviewers: ApiMethod
    workItemDetails: ApiMethod
  }
  hooks: {
    check: ApiMethod
    inspectSetupScriptImports: ApiMethod
    readIssueCommand: ApiMethod
    writeIssueCommand: ApiMethod
  }
  hostedReview: {
    create: ApiMethod
    forBranch: ApiMethod
    getCreationEligibility: ApiMethod
  }
  keybindings: {
    ensureFile: ApiMethod
    get: ApiMethod
    openFile: ApiMethod
    reload: ApiMethod
    revealFile: ApiMethod
    setAction: ApiMethod
    onChanged: ApiEvent
  }
  linear: {
    addIssueComment: ApiMethod
    connect: ApiMethod
    createIssue: ApiMethod
    disconnect: ApiMethod
    getCustomView: ApiMethod
    getIssue: ApiMethod
    getProject: ApiMethod
    issueComments: ApiMethod
    listCustomViewIssues: ApiMethod
    listCustomViewProjects: ApiMethod
    listCustomViews: ApiMethod
    listIssues: ApiMethod
    listProjectIssues: ApiMethod
    listProjects: ApiMethod
    listTeams: ApiMethod
    searchIssues: ApiMethod
    selectWorkspace: ApiMethod
    status: ApiMethod
    teamLabels: ApiMethod
    teamMembers: ApiMethod
    teamStates: ApiMethod
    testConnection: ApiMethod
    updateIssue: ApiMethod
  }
  mobile: {
    getRuntimePairingUrl: ApiMethod
    listNetworkInterfaces: ApiMethod
    listRuntimeAccessGrants: ApiMethod
    revokeRuntimeAccess: ApiMethod
  }
  notebook: {
    runPythonCell: ApiMethod
  }
  notifications: {
    dispatch: ApiMethod
    getPermissionStatus: ApiMethod
    openSystemSettings: ApiMethod
    playSound: ApiMethod
    requestPermission: ApiMethod
  }
  onboarding: {
    get: ApiMethod
    update: ApiMethod
  }
  openCodeUsage: {
    getBreakdown: ApiMethod
    getDaily: ApiMethod
    getRecentSessions: ApiMethod
    getScanState: ApiMethod
    getSummary: ApiMethod
    refresh: ApiMethod
    setEnabled: ApiMethod
  }
  pet: {
    delete: ApiMethod
    import: ApiMethod
    importPetBundle: ApiMethod
    read: ApiMethod
  }
  preflight: {
    check: ApiMethod
  }
  projectGroups: {
    create: ApiMethod
    delete: ApiMethod
    importNested: ApiMethod
    list: ApiMethod
    moveProject: ApiMethod
    scanNested: ApiMethod
    update: ApiMethod
  }
  pty: {
    ackColdRestore: ApiMethod
    clearPendingPaneSerializer: ApiMethod
    declarePendingPaneSerializer: ApiMethod
    getCwd: ApiMethod
    getForegroundProcess: ApiMethod
    getMainBufferSnapshot: ApiMethod
    hasChildProcesses: ApiMethod
    kill: ApiMethod
    listSessions: ApiMethod
    pauseOutput: ApiMethod
    resize: ApiMethod
    sendSerializedBuffer: ApiMethod
    settlePaneSerializer: ApiMethod
    signal: ApiMethod
    spawn: ApiMethod
    write: ApiMethod
    writeAccepted: ApiMethod
    management: {
      killAll: ApiMethod
      killOne: ApiMethod
      listSessions: ApiMethod
      restart: ApiMethod
    }
    onClearBufferRequest: ApiEvent
    onData: ApiEvent
    onExit: ApiEvent
    onReplay: ApiEvent
    onSerializeBufferRequest: ApiEvent
  }
  pwsh: {
    isAvailable: ApiMethod
  }
  rateLimits: {
    fetchInactiveClaudeAccounts: ApiMethod
    fetchInactiveCodexAccounts: ApiMethod
    get: ApiMethod
    refresh: ApiMethod
    refreshClaudeForTarget: ApiMethod
    refreshCodexForTarget: ApiMethod
    onUpdate: ApiEvent
  }
  remoteWorkspace: {
    get: ApiMethod
    setForConnectedTargets: ApiMethod
    onChanged: ApiEvent
  }
  repos: {
    add: ApiMethod
    addRemote: ApiMethod
    clone: ApiMethod
    cloneAbort: ApiMethod
    create: ApiMethod
    getBaseRefDefault: ApiMethod
    list: ApiMethod
    pickDirectory: ApiMethod
    pickFolder: ApiMethod
    remove: ApiMethod
    reorder: ApiMethod
    searchBaseRefDetails: ApiMethod
    searchBaseRefs: ApiMethod
    update: ApiMethod
    onChanged: ApiEvent
    onCloneProgress: ApiEvent
  }
  runtime: {
    call: ApiMethod
    syncWindowGraph: ApiMethod
  }
  runtimeEnvironments: {
    addFromPairingCode: ApiMethod
    call: ApiMethod
    list: ApiMethod
    remove: ApiMethod
    subscribe: ApiMethod
  }
  session: {
    get: ApiMethod
    patch: ApiMethod
    setSync: ApiMethod
  }
  settings: {
    get: ApiMethod
    listFonts: ApiMethod
    previewGhosttyImport: ApiMethod
    set: ApiMethod
    onChanged: ApiEvent
  }
  shell: {
    copyFile: ApiMethod
    openFilePath: ApiMethod
    openFileUri: ApiMethod
    openInExternalEditor: ApiMethod
    openInFileManager: ApiMethod
    openPath: ApiMethod
    openUrl: ApiMethod
    pathExists: ApiMethod
    pickAttachment: ApiMethod
    pickAudio: ApiMethod
    pickDirectory: ApiMethod
    pickImage: ApiMethod
    pickRepoIconImage: ApiMethod
  }
  skills: {
    discover: ApiMethod
  }
  sparsePresets: {
    list: ApiMethod
    remove: ApiMethod
    save: ApiMethod
  }
  speech: {
    feedAudio: ApiMethod
    getModelStates: ApiMethod
    startDictation: ApiMethod
    stopDictation: ApiMethod
    onDownloadProgress: ApiEvent
    onError: ApiEvent
    onFinalTranscript: ApiEvent
    onPartialTranscript: ApiEvent
    onStopped: ApiEvent
  }
  ssh: {
    addPortForward: ApiMethod
    addTarget: ApiMethod
    browseDir: ApiMethod
    connect: ApiMethod
    disconnect: ApiMethod
    getState: ApiMethod
    importConfig: ApiMethod
    listDetectedPorts: ApiMethod
    listPortForwards: ApiMethod
    listTargets: ApiMethod
    needsPassphrasePrompt: ApiMethod
    removePortForward: ApiMethod
    resetRelay: ApiMethod
    submitCredential: ApiMethod
    terminateSessions: ApiMethod
    testConnection: ApiMethod
    updatePortForward: ApiMethod
    updateTarget: ApiMethod
    onCredentialRequest: ApiEvent
    onCredentialResolved: ApiEvent
    onDetectedPortsChanged: ApiEvent
    onPortForwardsChanged: ApiEvent
    onStateChanged: ApiEvent
  }
  starNag: {
    complete: ApiMethod
    dismiss: ApiMethod
    onShow: ApiEvent
  }
  stats: {
    getSummary: ApiMethod
  }
  ui: {
    confirmWindowClose: ApiMethod
    get: ApiMethod
    getZoomLevel: ApiMethod
    isMaximized: ApiMethod
    maximize: ApiMethod
    minimize: ApiMethod
    popupMenu: ApiMethod
    readClipboardText: ApiMethod
    recordFeatureInteraction: ApiMethod
    replyTabClose: ApiMethod
    replyTabCreate: ApiMethod
    replyTabSetProfile: ApiMethod
    replyTerminalCreate: ApiMethod
    requestClose: ApiMethod
    saveClipboardImageAsTempFile: ApiMethod
    set: ApiMethod
    setFloatingTerminalInputFocused: ApiMethod
    setMarkdownEditorFocused: ApiMethod
    setShortcutRecorderFocused: ApiMethod
    setTerminalInputFocused: ApiMethod
    setZoomLevel: ApiMethod
    syncTrafficLights: ApiMethod
    writeClipboardImage: ApiMethod
    writeClipboardText: ApiMethod
    onActivateWorktree: ApiEvent
    onCloseActiveTab: ApiEvent
    onCloseSessionTab: ApiEvent
    onCloseTerminal: ApiEvent
    onCreateTerminal: ApiEvent
    onCtrlTabKeyDown: ApiEvent
    onCtrlTabKeyUp: ApiEvent
    onDeleteCurrentWorkspace: ApiEvent
    onDictationKeyDown: ApiEvent
    onExportPdfRequested: ApiEvent
    onFileDrop: ApiEvent
    onFindInBrowserPage: ApiEvent
    onFocusBrowserAddressBar: ApiEvent
    onFocusEditorTab: ApiEvent
    onFocusTerminal: ApiEvent
    onFullscreenChanged: ApiEvent
    onHardReloadBrowserPage: ApiEvent
    onJumpToTabIndex: ApiEvent
    onJumpToWorktreeIndex: ApiEvent
    onMaximizeChanged: ApiEvent
    onMoveSessionTab: ApiEvent
    onNewBrowserTab: ApiEvent
    onNewMarkdownTab: ApiEvent
    onNewTerminalTab: ApiEvent
    onOpenCrashReport: ApiEvent
    onOpenFeatureTour: ApiEvent
    onOpenNewWorkspace: ApiEvent
    onOpenQuickOpen: ApiEvent
    onOpenSettings: ApiEvent
    onOpenTasks: ApiEvent
    onReloadBrowserPage: ApiEvent
    onRenameTerminal: ApiEvent
    onRequestTabClose: ApiEvent
    onRequestTabCreate: ApiEvent
    onRequestTabSetProfile: ApiEvent
    onRequestTerminalCreate: ApiEvent
    onRichMarkdownContextCommand: ApiEvent
    onSleepWorktree: ApiEvent
    onSplitTerminal: ApiEvent
    onSwitchRecentTab: ApiEvent
    onSwitchTab: ApiEvent
    onSwitchTabAcrossAllTypes: ApiEvent
    onSwitchTerminalTab: ApiEvent
    onTerminalShortcutCaptured: ApiEvent
    onTerminalZoom: ApiEvent
    onToggleFloatingTerminal: ApiEvent
    onToggleLeftSidebar: ApiEvent
    onToggleRightSidebar: ApiEvent
    onToggleStatusBar: ApiEvent
    onToggleWorktreePalette: ApiEvent
    onWindowCloseRequested: ApiEvent
    onWorktreeHistoryNavigate: ApiEvent
  }
  updater: {
    check: ApiMethod
    dismissNudge: ApiMethod
    download: ApiMethod
    getStatus: ApiMethod
    getVersion: ApiMethod
    quitAndInstall: ApiMethod
    onClearDismissal: ApiEvent
    onStatus: ApiEvent
  }
  workspaceCleanup: {
    clearDismissals: ApiMethod
    dismiss: ApiMethod
    scan: ApiMethod
  }
  workspacePorts: {
    kill: ApiMethod
    scan: ApiMethod
    onAdvertisedUrlChanged: ApiEvent
  }
  workspaceSpace: {
    cancel: ApiMethod
  }
  worktrees: {
    create: ApiMethod
    forceDeletePreservedBranch: ApiMethod
    listDetected: ApiMethod
    listLineage: ApiMethod
    persistSortOrder: ApiMethod
    remove: ApiMethod
    resolvePrBase: ApiMethod
    updateLineage: ApiMethod
    updateMeta: ApiMethod
    onBaseStatus: ApiEvent
    onChanged: ApiEvent
    onRemoteBranchConflict: ApiEvent
  }
  wsl: {
    isAvailable: ApiMethod
    listDistros: ApiMethod
  }
  telemetryAcknowledgeBanner: ApiMethod
  telemetryGetConsentState: ApiMethod
  telemetrySetOptIn: ApiMethod
  telemetryTrack: ApiMethod
}
