// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const crashReports = defineNamespace('crashReports', {
  copyLatestDiagnostics: (...args: any[]) => call('crash_reports_copy_latest_diagnostics', args),
  dismiss: (...args: any[]) => call('crash_reports_dismiss', args),
  getLatestPending: (...args: any[]) => call('crash_reports_get_latest_pending', args),
  getLatestReport: (...args: any[]) => call('crash_reports_get_latest_report', args),
  submit: (...args: any[]) => call('crash_reports_submit', args),
}) satisfies AgentumApi['crashReports']
