// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const developerPermissions = defineNamespace('developerPermissions', {
  getStatus: (...args: any[]) => call('developer_permissions_get_status', args),
  request: (...args: any[]) => call('developer_permissions_request', args),
}) satisfies AgentumApi['developerPermissions']
