// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const diagnostics = defineNamespace('diagnostics', {
  clearTraces: (...args: any[]) => call('diagnostics_clear_traces', args),
  collectBundle: (...args: any[]) => call('diagnostics_collect_bundle', args),
  deleteBundle: (...args: any[]) => call('diagnostics_delete_bundle', args),
  discardBundlePreview: (...args: any[]) => call('diagnostics_discard_bundle_preview', args),
  getStatus: (...args: any[]) => call('diagnostics_get_status', args),
  openBundlePreview: (...args: any[]) => call('diagnostics_open_bundle_preview', args),
  openTraceFolder: (...args: any[]) => call('diagnostics_open_trace_folder', args),
  uploadBundle: (...args: any[]) => call('diagnostics_upload_bundle', args),
}) satisfies AgentumApi['diagnostics']
