// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const e2e = defineNamespace('e2e', {
  getConfig: (...args: any[]) => call('e2e_get_config', args),
}) satisfies AgentumApi['e2e']
