// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const fs = defineNamespace('fs', {
  authorizeExternalPath: (...args: any[]) => call('fs_authorize_external_path', args),
  copy: (...args: any[]) => call('fs_copy', args),
  createDir: (...args: any[]) => call('fs_create_dir', args),
  createFile: (...args: any[]) => call('fs_create_file', args),
  deletePath: (...args: any[]) => call('fs_delete_path', args),
  importExternalPaths: (...args: any[]) => call('fs_import_external_paths', args),
  listFiles: (...args: any[]) => call('fs_list_files', args),
  listMarkdownDocuments: (...args: any[]) => call('fs_list_markdown_documents', args),
  readDir: (...args: any[]) => call('fs_read_dir', args),
  readFile: (...args: any[]) => call('fs_read_file', args),
  rename: (...args: any[]) => call('fs_rename', args),
  resolveDroppedPathsForAgent: (...args: any[]) => call('fs_resolve_dropped_paths_for_agent', args),
  search: (...args: any[]) => call('fs_search', args),
  stageExternalPathsForRuntimeUpload: (...args: any[]) => call('fs_stage_external_paths_for_runtime_upload', args),
  stat: (...args: any[]) => call('fs_stat', args),
  unwatchWorktree: (...args: any[]) => call('fs_unwatch_worktree', args),
  writeFile: (...args: any[]) => call('fs_write_file', args),
  onFsChanged: (cb: (p: any) => void) => subscribe('fs-fs-changed', cb),
}) satisfies AgentumApi['fs']
