// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const git = defineNamespace('git', {
  abortMerge: (...args: any[]) => call('git_abort_merge', args),
  abortRebase: (...args: any[]) => call('git_abort_rebase', args),
  branchCompare: (...args: any[]) => call('git_branch_compare', args),
  branchDiff: (...args: any[]) => call('git_branch_diff', args),
  bulkDiscard: (...args: any[]) => call('git_bulk_discard', args),
  bulkStage: (...args: any[]) => call('git_bulk_stage', args),
  bulkUnstage: (...args: any[]) => call('git_bulk_unstage', args),
  cancelGenerateCommitMessage: (...args: any[]) => call('git_cancel_generate_commit_message', args),
  cancelGeneratePullRequestFields: (...args: any[]) => call('git_cancel_generate_pull_request_fields', args),
  checkIgnored: (...args: any[]) => call('git_check_ignored', args),
  commit: (...args: any[]) => call('git_commit', args),
  commitCompare: (...args: any[]) => call('git_commit_compare', args),
  commitDiff: (...args: any[]) => call('git_commit_diff', args),
  conflictOperation: (...args: any[]) => call('git_conflict_operation', args),
  diff: (...args: any[]) => call('git_diff', args),
  discard: (...args: any[]) => call('git_discard', args),
  discoverCommitMessageModels: (...args: any[]) => call('git_discover_commit_message_models', args),
  fastForward: (...args: any[]) => call('git_fast_forward', args),
  fetch: (...args: any[]) => call('git_fetch', args),
  generateCommitMessage: (...args: any[]) => call('git_generate_commit_message', args),
  generatePullRequestFields: (...args: any[]) => call('git_generate_pull_request_fields', args),
  history: (...args: any[]) => call('git_history', args),
  pull: (...args: any[]) => call('git_pull', args),
  push: (...args: any[]) => call('git_push', args),
  rebaseFromBase: (...args: any[]) => call('git_rebase_from_base', args),
  remoteFileUrl: (...args: any[]) => call('git_remote_file_url', args),
  stage: (...args: any[]) => call('git_stage', args),
  status: (...args: any[]) => call('git_status', args),
  unstage: (...args: any[]) => call('git_unstage', args),
  upstreamStatus: (...args: any[]) => call('git_upstream_status', args),
}) satisfies AgentumApi['git']
