// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const gitBash = defineNamespace('gitBash', {
  isAvailable: (...args: any[]) => call('git_bash_is_available', args),
}) satisfies AgentumApi['gitBash']
