// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const gl = defineNamespace('gl', {
  addIssueComment: (...args: any[]) => call('gl_add_issue_comment', args),
  addMRComment: (...args: any[]) => call('gl_add_mr_comment', args),
  addMRInlineComment: (...args: any[]) => call('gl_add_mr_inline_comment', args),
  closeMR: (...args: any[]) => call('gl_close_mr', args),
  jobTrace: (...args: any[]) => call('gl_job_trace', args),
  listAssignableUsers: (...args: any[]) => call('gl_list_assignable_users', args),
  listLabels: (...args: any[]) => call('gl_list_labels', args),
  listMRs: (...args: any[]) => call('gl_list_m_rs', args),
  mergeMR: (...args: any[]) => call('gl_merge_mr', args),
  rateLimit: (...args: any[]) => call('gl_rate_limit', args),
  reopenMR: (...args: any[]) => call('gl_reopen_mr', args),
  resolveMRDiscussion: (...args: any[]) => call('gl_resolve_mr_discussion', args),
  retryJob: (...args: any[]) => call('gl_retry_job', args),
  updateMR: (...args: any[]) => call('gl_update_mr', args),
  updateMRReviewers: (...args: any[]) => call('gl_update_mr_reviewers', args),
  workItemDetails: (...args: any[]) => call('gl_work_item_details', args),
}) satisfies AgentumApi['gl']
