// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const hooks = defineNamespace('hooks', {
  check: (...args: any[]) => call('hooks_check', args),
  inspectSetupScriptImports: (...args: any[]) => call('hooks_inspect_setup_script_imports', args),
  readIssueCommand: (...args: any[]) => call('hooks_read_issue_command', args),
  writeIssueCommand: (...args: any[]) => call('hooks_write_issue_command', args),
}) satisfies AgentumApi['hooks']
