// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const hostedReview = defineNamespace('hostedReview', {
  create: (...args: any[]) => call('hosted_review_create', args),
  forBranch: (...args: any[]) => call('hosted_review_for_branch', args),
  getCreationEligibility: (...args: any[]) => call('hosted_review_get_creation_eligibility', args),
}) satisfies AgentumApi['hostedReview']
