// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call } from './core'
import type { AgentumApi } from './contract'
import { agentStatus } from './agentStatus'
import { agentTrust } from './agentTrust'
import { app } from './app'
import { browser } from './browser'
import { cache } from './cache'
import { claudeAccounts } from './claudeAccounts'
import { claudeUsage } from './claudeUsage'
import { cli } from './cli'
import { codexAccounts } from './codexAccounts'
import { codexUsage } from './codexUsage'
import { computerUsePermissions } from './computerUsePermissions'
import { crashReports } from './crashReports'
import { developerPermissions } from './developerPermissions'
import { diagnostics } from './diagnostics'
import { e2e } from './e2e'
import { exportApi } from './export'
import { feedback } from './feedback'
import { fs } from './fs'
import { gh } from './gh'
import { gitBash } from './gitBash'
import { gl } from './gl'
import { hooks } from './hooks'
import { hostedReview } from './hostedReview'
import { keybindings } from './keybindings'
import { linear } from './linear'
import { mobile } from './mobile'
import { notebook } from './notebook'
import { notifications } from './notifications'
import { onboarding } from './onboarding'
import { openCodeUsage } from './openCodeUsage'
import { pet } from './pet'
import { preflight } from './preflight'
import { projectGroups } from './projectGroups'
import { pty } from './pty'
import { pwsh } from './pwsh'
import { rateLimits } from './rateLimits'
import { remoteWorkspace } from './remoteWorkspace'
import { repos } from './repos'
import { runtime } from './runtime'
import { runtimeEnvironments } from './runtimeEnvironments'
import { session } from './session'
import { settings } from './settings'
import { shell } from './shell'
import { skills } from './skills'
import { sparsePresets } from './sparsePresets'
import { speech } from './speech'
import { ssh } from './ssh'
import { starNag } from './starNag'
import { stats } from './stats'
import { ui } from './ui'
import { updater } from './updater'
import { workspaceCleanup } from './workspaceCleanup'
import { workspacePorts } from './workspacePorts'
import { worktrees } from './worktrees'
import { wsl } from './wsl'

export type { AgentumApi } from './contract'

export const api: AgentumApi = {
  agentStatus,
  agentTrust,
  app,
  browser,
  cache,
  claudeAccounts,
  claudeUsage,
  cli,
  codexAccounts,
  codexUsage,
  computerUsePermissions,
  crashReports,
  developerPermissions,
  diagnostics,
  e2e,
  export: exportApi,
  feedback,
  fs,
  gh,
  gitBash,
  gl,
  hooks,
  hostedReview,
  keybindings,
  linear,
  mobile,
  notebook,
  notifications,
  onboarding,
  openCodeUsage,
  pet,
  preflight,
  projectGroups,
  pty,
  pwsh,
  rateLimits,
  remoteWorkspace,
  repos,
  runtime,
  runtimeEnvironments,
  session,
  settings,
  shell,
  skills,
  sparsePresets,
  speech,
  ssh,
  starNag,
  stats,
  ui,
  updater,
  workspaceCleanup,
  workspacePorts,
  worktrees,
  wsl,
  telemetryAcknowledgeBanner: (...args: any[]) => call('telemetry_acknowledge_banner', args),
  telemetryGetConsentState: (...args: any[]) => call('telemetry_get_consent_state', args),
  telemetrySetOptIn: (...args: any[]) => call('telemetry_set_opt_in', args),
  telemetryTrack: (...args: any[]) => call('telemetry_track', args),
}
