// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const keybindings = defineNamespace('keybindings', {
  ensureFile: (...args: any[]) => call('keybindings_ensure_file', args),
  get: (...args: any[]) => call('keybindings_get', args),
  openFile: (...args: any[]) => call('keybindings_open_file', args),
  reload: (...args: any[]) => call('keybindings_reload', args),
  revealFile: (...args: any[]) => call('keybindings_reveal_file', args),
  setAction: (...args: any[]) => call('keybindings_set_action', args),
  onChanged: (cb: (p: any) => void) => subscribe('keybindings-changed', cb),
}) satisfies AgentumApi['keybindings']
