// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const linear = defineNamespace('linear', {
  addIssueComment: (...args: any[]) => call('linear_add_issue_comment', args),
  connect: (...args: any[]) => call('linear_connect', args),
  createIssue: (...args: any[]) => call('linear_create_issue', args),
  disconnect: (...args: any[]) => call('linear_disconnect', args),
  getCustomView: (...args: any[]) => call('linear_get_custom_view', args),
  getIssue: (...args: any[]) => call('linear_get_issue', args),
  getProject: (...args: any[]) => call('linear_get_project', args),
  getStateMap: (...args: any[]) => call('linear_get_state_map', args),
  setStateMap: (...args: any[]) => call('linear_set_state_map', args),
  issueComments: (...args: any[]) => call('linear_issue_comments', args),
  listCustomViewIssues: (...args: any[]) => call('linear_list_custom_view_issues', args),
  listCustomViewProjects: (...args: any[]) => call('linear_list_custom_view_projects', args),
  listCustomViews: (...args: any[]) => call('linear_list_custom_views', args),
  listIssues: (...args: any[]) => call('linear_list_issues', args),
  listProjectIssues: (...args: any[]) => call('linear_list_project_issues', args),
  listProjects: (...args: any[]) => call('linear_list_projects', args),
  listTeams: (...args: any[]) => call('linear_list_teams', args),
  searchIssues: (...args: any[]) => call('linear_search_issues', args),
  selectWorkspace: (...args: any[]) => call('linear_select_workspace', args),
  status: (...args: any[]) => call('linear_status', args),
  teamLabels: (...args: any[]) => call('linear_team_labels', args),
  teamMembers: (...args: any[]) => call('linear_team_members', args),
  teamStates: (...args: any[]) => call('linear_team_states', args),
  testConnection: (...args: any[]) => call('linear_test_connection', args),
  updateIssue: (...args: any[]) => call('linear_update_issue', args),
}) satisfies AgentumApi['linear']
