// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const memory = defineNamespace('memory', {
  getSnapshot: (...args: any[]) => call('memory_get_snapshot', args),
}) satisfies AgentumApi['memory']
