// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const mobile = defineNamespace('mobile', {
  getRuntimePairingUrl: (...args: any[]) => call('mobile_get_runtime_pairing_url', args),
  listNetworkInterfaces: (...args: any[]) => call('mobile_list_network_interfaces', args),
  listRuntimeAccessGrants: (...args: any[]) => call('mobile_list_runtime_access_grants', args),
  revokeRuntimeAccess: (...args: any[]) => call('mobile_revoke_runtime_access', args),
}) satisfies AgentumApi['mobile']
