// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const notebook = defineNamespace('notebook', {
  runPythonCell: (...args: any[]) => call('notebook_run_python_cell', args),
}) satisfies AgentumApi['notebook']
