// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const notifications = defineNamespace('notifications', {
  dispatch: (...args: any[]) => call('notifications_dispatch', args),
  getPermissionStatus: (...args: any[]) => call('notifications_get_permission_status', args),
  openSystemSettings: (...args: any[]) => call('notifications_open_system_settings', args),
  playSound: (...args: any[]) => call('notifications_play_sound', args),
  requestPermission: (...args: any[]) => call('notifications_request_permission', args),
}) satisfies AgentumApi['notifications']
