// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const onboarding = defineNamespace('onboarding', {
  get: (...args: any[]) => call('onboarding_get', args),
  update: (...args: any[]) => call('onboarding_update', args),
}) satisfies AgentumApi['onboarding']
