// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const pet = defineNamespace('pet', {
  delete: (...args: any[]) => call('pet_delete', args),
  import: (...args: any[]) => call('pet_import', args),
  importPetBundle: (...args: any[]) => call('pet_import_pet_bundle', args),
  read: (...args: any[]) => call('pet_read', args),
}) satisfies AgentumApi['pet']
