// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const projectGroups = defineNamespace('projectGroups', {
  create: (...args: any[]) => call('project_groups_create', args),
  delete: (...args: any[]) => call('project_groups_delete', args),
  importNested: (...args: any[]) => call('project_groups_import_nested', args),
  list: (...args: any[]) => call('project_groups_list', args),
  moveProject: (...args: any[]) => call('project_groups_move_project', args),
  scanNested: (...args: any[]) => call('project_groups_scan_nested', args),
  update: (...args: any[]) => call('project_groups_update', args),
}) satisfies AgentumApi['projectGroups']
