// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const pty = defineNamespace('pty', {
  ackColdRestore: (...args: any[]) => call('pty_ack_cold_restore', args),
  clearPendingPaneSerializer: (...args: any[]) => call('pty_clear_pending_pane_serializer', args),
  declarePendingPaneSerializer: (...args: any[]) => call('pty_declare_pending_pane_serializer', args),
  getCwd: (...args: any[]) => call('pty_get_cwd', args),
  getForegroundProcess: (...args: any[]) => call('pty_get_foreground_process', args),
  getMainBufferSnapshot: (...args: any[]) => call('pty_get_main_buffer_snapshot', args),
  hasChildProcesses: (...args: any[]) => call('pty_has_child_processes', args),
  kill: (...args: any[]) => call('pty_kill', args),
  listSessions: (...args: any[]) => call('pty_list_sessions', args),
  pauseOutput: (...args: any[]) => call('pty_pause_output', args),
  resize: (...args: any[]) => call('pty_resize', args),
  sendSerializedBuffer: (...args: any[]) => call('pty_send_serialized_buffer', args),
  settlePaneSerializer: (...args: any[]) => call('pty_settle_pane_serializer', args),
  signal: (...args: any[]) => call('pty_signal', args),
  spawn: (...args: any[]) => call('pty_spawn', args),
  write: (...args: any[]) => call('pty_write', args),
  writeAccepted: (...args: any[]) => call('pty_write_accepted', args),
  management: {
    killAll: (...args: any[]) => call('pty_management_kill_all', args),
    killOne: (...args: any[]) => call('pty_management_kill_one', args),
    listSessions: (...args: any[]) => call('pty_management_list_sessions', args),
    restart: (...args: any[]) => call('pty_management_restart', args),
  },
  onClearBufferRequest: (cb: (p: any) => void) => subscribe('pty-clear-buffer-request', cb),
  onData: (cb: (p: any) => void) => subscribe('pty-data', cb),
  onExit: (cb: (p: any) => void) => subscribe('pty-exit', cb),
  onReplay: (cb: (p: any) => void) => subscribe('pty-replay', cb),
  onSerializeBufferRequest: (cb: (p: any) => void) => subscribe('pty-serialize-buffer-request', cb),
}) satisfies AgentumApi['pty']
