// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const pwsh = defineNamespace('pwsh', {
  isAvailable: (...args: any[]) => call('pwsh_is_available', args),
}) satisfies AgentumApi['pwsh']
