// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const rateLimits = defineNamespace('rateLimits', {
  fetchInactiveClaudeAccounts: (...args: any[]) => call('rate_limits_fetch_inactive_claude_accounts', args),
  fetchInactiveCodexAccounts: (...args: any[]) => call('rate_limits_fetch_inactive_codex_accounts', args),
  get: (...args: any[]) => call('rate_limits_get', args),
  refresh: (...args: any[]) => call('rate_limits_refresh', args),
  refreshClaudeForTarget: (...args: any[]) => call('rate_limits_refresh_claude_for_target', args),
  refreshCodexForTarget: (...args: any[]) => call('rate_limits_refresh_codex_for_target', args),
  onUpdate: (cb: (p: any) => void) => subscribe('rate-limits-update', cb),
}) satisfies AgentumApi['rateLimits']
