// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const remoteWorkspace = defineNamespace('remoteWorkspace', {
  get: (...args: any[]) => call('remote_workspace_get', args),
  setForConnectedTargets: (...args: any[]) => call('remote_workspace_set_for_connected_targets', args),
  onChanged: (cb: (p: any) => void) => subscribe('remote-workspace-changed', cb),
}) satisfies AgentumApi['remoteWorkspace']
