// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const repos = defineNamespace('repos', {
  add: (...args: any[]) => call('repos_add', args),
  addRemote: (...args: any[]) => call('repos_add_remote', args),
  clone: (...args: any[]) => call('repos_clone', args),
  cloneAbort: (...args: any[]) => call('repos_clone_abort', args),
  create: (...args: any[]) => call('repos_create', args),
  getBaseRefDefault: (...args: any[]) => call('repos_get_base_ref_default', args),
  list: (...args: any[]) => call('repos_list', args),
  pickDirectory: (...args: any[]) => call('repos_pick_directory', args),
  pickFolder: (...args: any[]) => call('repos_pick_folder', args),
  remove: (...args: any[]) => call('repos_remove', args),
  reorder: (...args: any[]) => call('repos_reorder', args),
  searchBaseRefDetails: (...args: any[]) => call('repos_search_base_ref_details', args),
  searchBaseRefs: (...args: any[]) => call('repos_search_base_refs', args),
  update: (...args: any[]) => call('repos_update', args),
  onChanged: (cb: (p: any) => void) => subscribe('repos-changed', cb),
  onCloneProgress: (cb: (p: any) => void) => subscribe('repos-clone-progress', cb),
}) satisfies AgentumApi['repos']
