// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const runtimeEnvironments = defineNamespace('runtimeEnvironments', {
  addFromPairingCode: (...args: any[]) => call('runtime_environments_add_from_pairing_code', args),
  call: (...args: any[]) => call('runtime_environments_call', args),
  list: (...args: any[]) => call('runtime_environments_list', args),
  remove: (...args: any[]) => call('runtime_environments_remove', args),
  subscribe: (...args: any[]) => call('runtime_environments_subscribe', args),
}) satisfies AgentumApi['runtimeEnvironments']
