// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const runtime = defineNamespace('runtime', {
  call: (...args: any[]) => call('runtime_call', args),
  syncWindowGraph: (...args: any[]) => call('runtime_sync_window_graph', args),
}) satisfies AgentumApi['runtime']
