// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const session = defineNamespace('session', {
  get: (...args: any[]) => call('session_get', args),
  patch: (...args: any[]) => call('session_patch', args),
  setSync: (...args: any[]) => call('session_set_sync', args),
}) satisfies AgentumApi['session']
