// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const settings = defineNamespace('settings', {
  get: (...args: any[]) => call('settings_get', args),
  listFonts: (...args: any[]) => call('settings_list_fonts', args),
  previewGhosttyImport: (...args: any[]) => call('settings_preview_ghostty_import', args),
  set: (...args: any[]) => call('settings_set', args),
  onChanged: (cb: (p: any) => void) => subscribe('settings-changed', cb),
}) satisfies AgentumApi['settings']
