// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const shell = defineNamespace('shell', {
  copyFile: (...args: any[]) => call('shell_copy_file', args),
  openFilePath: (...args: any[]) => call('shell_open_file_path', args),
  openFileUri: (...args: any[]) => call('shell_open_file_uri', args),
  openInExternalEditor: (...args: any[]) => call('shell_open_in_external_editor', args),
  openInFileManager: (...args: any[]) => call('shell_open_in_file_manager', args),
  openPath: (...args: any[]) => call('shell_open_path', args),
  openUrl: (...args: any[]) => call('shell_open_url', args),
  pathExists: (...args: any[]) => call('shell_path_exists', args),
  pickAttachment: (...args: any[]) => call('shell_pick_attachment', args),
  pickAudio: (...args: any[]) => call('shell_pick_audio', args),
  pickDirectory: (...args: any[]) => call('shell_pick_directory', args),
  pickImage: (...args: any[]) => call('shell_pick_image', args),
  pickRepoIconImage: (...args: any[]) => call('shell_pick_repo_icon_image', args),
}) satisfies AgentumApi['shell']
