// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const sparsePresets = defineNamespace('sparsePresets', {
  list: (...args: any[]) => call('sparse_presets_list', args),
  remove: (...args: any[]) => call('sparse_presets_remove', args),
  save: (...args: any[]) => call('sparse_presets_save', args),
}) satisfies AgentumApi['sparsePresets']
