// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const speech = defineNamespace('speech', {
  feedAudio: (...args: any[]) => call('speech_feed_audio', args),
  getModelStates: (...args: any[]) => call('speech_get_model_states', args),
  startDictation: (...args: any[]) => call('speech_start_dictation', args),
  stopDictation: (...args: any[]) => call('speech_stop_dictation', args),
  onDownloadProgress: (cb: (p: any) => void) => subscribe('speech-download-progress', cb),
  onError: (cb: (p: any) => void) => subscribe('speech-error', cb),
  onFinalTranscript: (cb: (p: any) => void) => subscribe('speech-final-transcript', cb),
  onPartialTranscript: (cb: (p: any) => void) => subscribe('speech-partial-transcript', cb),
  onStopped: (cb: (p: any) => void) => subscribe('speech-stopped', cb),
}) satisfies AgentumApi['speech']
