// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const ssh = defineNamespace('ssh', {
  addPortForward: (...args: any[]) => call('ssh_add_port_forward', args),
  addTarget: (...args: any[]) => call('ssh_add_target', args),
  browseDir: (...args: any[]) => call('ssh_browse_dir', args),
  connect: (...args: any[]) => call('ssh_connect', args),
  disconnect: (...args: any[]) => call('ssh_disconnect', args),
  getState: (...args: any[]) => call('ssh_get_state', args),
  importConfig: (...args: any[]) => call('ssh_import_config', args),
  listDetectedPorts: (...args: any[]) => call('ssh_list_detected_ports', args),
  listPortForwards: (...args: any[]) => call('ssh_list_port_forwards', args),
  listTargets: (...args: any[]) => call('ssh_list_targets', args),
  needsPassphrasePrompt: (...args: any[]) => call('ssh_needs_passphrase_prompt', args),
  removeTarget: (...args: any[]) => call('ssh_remove_target', args),
  removePortForward: (...args: any[]) => call('ssh_remove_port_forward', args),
  resetRelay: (...args: any[]) => call('ssh_reset_relay', args),
  submitCredential: (...args: any[]) => call('ssh_submit_credential', args),
  terminateSessions: (...args: any[]) => call('ssh_terminate_sessions', args),
  testConnection: (...args: any[]) => call('ssh_test_connection', args),
  updatePortForward: (...args: any[]) => call('ssh_update_port_forward', args),
  updateTarget: (...args: any[]) => call('ssh_update_target', args),
  onCredentialRequest: (cb: (p: any) => void) => subscribe('ssh-credential-request', cb),
  onCredentialResolved: (cb: (p: any) => void) => subscribe('ssh-credential-resolved', cb),
  onDetectedPortsChanged: (cb: (p: any) => void) => subscribe('ssh-detected-ports-changed', cb),
  onPortForwardsChanged: (cb: (p: any) => void) => subscribe('ssh-port-forwards-changed', cb),
  onStateChanged: (cb: (p: any) => void) => subscribe('ssh-state-changed', cb),
}) satisfies AgentumApi['ssh']
