// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const starNag = defineNamespace('starNag', {
  complete: (...args: any[]) => call('star_nag_complete', args),
  dismiss: (...args: any[]) => call('star_nag_dismiss', args),
  onShow: (cb: (p: any) => void) => subscribe('star-nag-show', cb),
}) satisfies AgentumApi['starNag']
