// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const stats = defineNamespace('stats', {
  getSummary: (...args: any[]) => call('stats_get_summary', args),
}) satisfies AgentumApi['stats']
