// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const updater = defineNamespace('updater', {
  check: (...args: any[]) => call('updater_check', args),
  dismissNudge: (...args: any[]) => call('updater_dismiss_nudge', args),
  download: (...args: any[]) => call('updater_download', args),
  getStatus: (...args: any[]) => call('updater_get_status', args),
  getVersion: (...args: any[]) => call('updater_get_version', args),
  quitAndInstall: (...args: any[]) => call('updater_quit_and_install', args),
  onClearDismissal: (cb: (p: any) => void) => subscribe('updater-clear-dismissal', cb),
  onStatus: (cb: (p: any) => void) => subscribe('updater-status', cb),
}) satisfies AgentumApi['updater']
