// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const workspacePorts = defineNamespace('workspacePorts', {
  kill: (...args: any[]) => call('workspace_ports_kill', args),
  scan: (...args: any[]) => call('workspace_ports_scan', args),
  onAdvertisedUrlChanged: (cb: (p: any) => void) => subscribe('workspace-ports-advertised-url-changed', cb),
}) satisfies AgentumApi['workspacePorts']
