// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const workspaceCleanup = defineNamespace('workspaceCleanup', {
  clearDismissals: (...args: any[]) => call('workspace_cleanup_clear_dismissals', args),
  dismiss: (...args: any[]) => call('workspace_cleanup_dismiss', args),
  scan: (...args: any[]) => call('workspace_cleanup_scan', args),
}) satisfies AgentumApi['workspaceCleanup']
