// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const worktrees = defineNamespace('worktrees', {
  create: (...args: any[]) => call('worktrees_create', args),
  forceDeletePreservedBranch: (...args: any[]) => call('worktrees_force_delete_preserved_branch', args),
  listDetected: (...args: any[]) => call('worktrees_list_detected', args),
  listLineage: (...args: any[]) => call('worktrees_list_lineage', args),
  persistSortOrder: (...args: any[]) => call('worktrees_persist_sort_order', args),
  remove: (...args: any[]) => call('worktrees_remove', args),
  resolvePrBase: (...args: any[]) => call('worktrees_resolve_pr_base', args),
  updateLineage: (...args: any[]) => call('worktrees_update_lineage', args),
  updateMeta: (...args: any[]) => call('worktrees_update_meta', args),
  onBaseStatus: (cb: (p: any) => void) => subscribe('worktrees-base-status', cb),
  onChanged: (cb: (p: any) => void) => subscribe('worktrees-changed', cb),
  onRemoteBranchConflict: (cb: (p: any) => void) => subscribe('worktrees-remote-branch-conflict', cb),
}) satisfies AgentumApi['worktrees']
