// AUTO-GENERATED by /tmp/gen-tauri-client.mjs — explicit typed Tauri client.
// Replaces lib/electron-bridge.ts proxy. Command/event names match the old wire contract.

import { call, subscribe, defineNamespace } from './core'
import type { AgentumApi } from './contract'

export const wsl = defineNamespace('wsl', {
  isAvailable: (...args: any[]) => call('wsl_is_available', args),
  listDistros: (...args: any[]) => call('wsl_list_distros', args),
}) satisfies AgentumApi['wsl']
